// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXe4WyHx69QpXiJcoPTwRacucZHClyn3o',
    appId: '1:847259151598:ios:c6d10972908bab7628d7ff',
    messagingSenderId: '847259151598',
    projectId: 'judy-home-healthcare',
    storageBucket: 'judy-home-healthcare.firebasestorage.app',
    iosBundleId: 'com.judyhealthcare.mobile',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQFnwD-r3ltQdaMdjrKprmat3Uw8hIqBg',
    appId: '1:847259151598:android:a5c7c507a0f8fec028d7ff',
    messagingSenderId: '847259151598',
    projectId: 'judy-home-healthcare',
    storageBucket: 'judy-home-healthcare.firebasestorage.app',
  );

}